### ISSUE TITLE
Sorting and filtering options for Character List

### ISSUE THREAD

**Issue by Jader7777** [Orcpub/orcpub#523] opened 2021-03-20 07:02 UTC
Please add the option to sort characters on your Character List via their features. Possible methods:

- Sort by class
- Sort by level
- Sort by name in the description
- Sort by last edited

The current format is just an extensive list of Characters and it becomes extremely difficult to navigate as your list grows:

![useful image](https://cdn.discordapp.com/attachments/458089668563566594/822726276540137472/unknown.png)

**Comment by datdamnzotz** [comment] 2021-03-20 17:27
Duplicate of #52

**Closed as completed by datdamnzotz** 2021-03-20 17:27 UTC
