### ISSUE TITLE
Allow the use of Spell Points

### ISSUE THREAD

**Issue by Jessomadic** [Orcpub/orcpub#451] opened 2020-09-20 13:50 UTC
**Motivation / Use Case**

Gives users more choices for how they want to play

**Expected Behavior**

A system that would allow a user to (Before PDF gen) chose to use the Spell Slots or the Spell Points systems of 5e and have the site grab the correct PDFs

**Comment by DivertedCircle** [comment] 2020-09-20 21:37
Duplicate of #440

**Closed as completed by DivertedCircle** 2020-09-20 21:37 UTC
