### ISSUE TITLE
Having the option to prepare a spell prevents learning the spell from another source

### ISSUE THREAD

**Issue by lorewalkercho** [Orcpub/orcpub#438] opened 2020-08-21 06:02 UTC
If you are granted the ability to prepare a spell through a class (such as Paladin and Detect Magic) and for a later level choose a class that can learn that spell (such as Sorcerer) that spell will be grayed out and cannot be selected, because "You already know this spell". This is a problem because even if you want to have a spell and have the ability to prepare it, you may not want to use a prepared spell slot for it. Other preparable spells may take priority and you may want to use a second class's learned spells to gain access without losing one of the higher-priority prepared spells.

I'm not sure what the ideal fix for this would be-maybe saying "you can already prepare this spell" but allowing it to be selected anyways?

**Comment by DivertedCircle** [comment] 2020-08-21 17:11
Duplicate of #47.

**Closed as completed by DivertedCircle** 2020-08-21 17:11 UTC
