### ISSUE TITLE
Characters List is not opening

### ISSUE THREAD

**Issue by kieragjzz** [Orcpub/orcpub#401] opened 2020-06-16 18:56 UTC
When I try to open the Characters List, I click on the button, the page starts charging but then the sreen becomes completely black. I cannot open the list anymore. Everything else works.

**To Reproduce**
1. Click on 'Characters List'
2. THe page doesn't open 
3. Black screen

![Cattura](https://user-images.githubusercontent.com/67021853/84815695-b1148280-b013-11ea-987c-fcaa940258d1.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by codeGlaze** [comment] 2020-06-25 02:02
@kieragjzz This is most likely related to your custom content.

There are a few bugs that pop up in custom content that cause JS error and send react into a spiral.

You can verify this by accessing your account in an incognito window with no custom content loaded.

You can disable files and reload the site to determine what's causing the error if you'd like.

**Comment by rhian713** [comment] 2020-08-31 18:34
I am running into the same issue, plus I cannot create new characters either. I can select a race and subrace for the character, but the class tab doesn't have any dropdown menu with the available classes. I have disabled all my homebrew content and I still get a blank screen when pulling up my character list. Pulling up an incognito window allows me to see my characters. 

Should I just trash all my homebrew content and start from scratch?

**Comment by DivertedCircle** [comment] 2020-08-31 19:37
If it works in incognito but not the base site, then you'll have to somehow isolate where the problem is coming from in your uploaded files. Starting fresh is also an option.

Closing because the person who opened the issue has not responded.

**Closed as completed by DivertedCircle** 2020-08-31 19:37 UTC
Labels: bug, area/application
