### ISSUE TITLE
Compact roll buttons

### ISSUE THREAD

**Issue by Pireax** [Orcpub/orcpub#427] opened 2020-07-18 15:05 UTC
**Motivation / Use Case**
The roll buttons are a nice addition but they take up a lot of space, I think it would be better to combine the roll button and the modifier for the roll into one to make it a bit more compact.

Below some quick mockups of how this could look:
![image](https://user-images.githubusercontent.com/11289656/87855353-f7f9de80-c917-11ea-9edb-50fdb5fa15f8.png)
![image](https://user-images.githubusercontent.com/11289656/87855446-b4ec3b00-c918-11ea-85f1-20fb9b6e589a.png)

As some mentioned, the damage is already in the details section making it a bit redundant, below an alternative with this fixed:
![image](https://user-images.githubusercontent.com/11289656/87882709-51d6d300-ca02-11ea-9030-65158af33ff0.png)

**Comment by codeGlaze** [comment] 2020-07-18 22:34
I like that. But it does make the use more opaque.

There's a significant chance most, or at least... Many, users won't notice those are actual buttons.

Thoughts?

**Comment by Pireax** [comment] 2020-07-18 22:52
I think that it is clear that they are buttons as the same button design is used for a lot of other actions on the website, the buttons would also still have tooltips so even if they don't notice that these are buttons they can discover it this way. (This same design is also applied in dndbeyond and worldanvil character sheets btw)

**Comment by codeGlaze** [comment] 2020-07-19 00:28
> This same design is also applied in dndbeyond and worldanvil character sheets btw

This actually puts me at ease with the decision. Looks like there might be room to add a *tiny* d20 icon or something>
But, all told, I definitely agree with the idea.

**Comment by datdamnzotz** [comment] 2020-07-19 06:50
On the fence about this one.  I'll toss it at the patrons and have them vote 👍 👎  on it.

Open for 7 days

**Comment by Butterfly-Dragon** [comment] 2020-07-19 07:04
works for me!

**Comment by leoherzog** [comment] 2020-07-19 11:25
I like the idea of the d20 icon. `🎲+2` or `2🎲+4` (substituting appropriate icons) would look sharp, and meaningful iconography where space is constrained is a common design practice.

**Comment by LumaDevelopment** [comment] 2020-07-19 14:15
I love the idea of the mockup posted by the original author.

The issue is finding a way to implement a dice symbol appropriate for the roll being made without morphing the size of the buttons. Perhaps we should just stick with the mock-up that started the issue as it is compact and clear. Smaller symbols might be hard to read and confusing for new players, especially if this theology is adapted in areas where the plaintext formula isn't listed.

**Comment by datdamnzotz** [comment] 2020-07-19 17:40
I think the question is how we do it so it is most clear : ]
Gotta think of the newbies and the seasoned vets. and getting it to work on mobile as well - and color challenged people.

**Comment by jrjohnson** [comment] 2020-07-19 21:56
New player here, I spent a lot of time trying to figure out what hitting the existing buttons would do and if it aligned with what our DM wanted us to roll. This seems like a good addition to make it clear what exactly is being used to roll.

**Comment by barefootcoder** [comment] 2020-07-21 00:05
Perhaps the graphic for the button itself could be shaped like a d20.  That would make it pretty obvious, and then just having "+4" or what-have-you would be plenty sufficient.

**Comment by datdamnzotz** [comment] 2020-07-28 20:12
Poll Results
![image](https://user-images.githubusercontent.com/3913859/88716487-60954800-d0dc-11ea-94d7-5fd7058e8fab.png)

**Comment by datdamnzotz** [comment] 2020-09-30 07:35
Resolved via #436

**Closed as completed** 2020-09-30 07:35 UTC
Labels: enhancement, area/application
