### ISSUE TITLE
Duel Fighter Style Not Applying

### ISSUE THREAD

**Issue by Legionof10** [Orcpub/orcpub#376] opened 2020-05-04 23:47 UTC
**Describe the bug**
Dueling Fighting Style does not apply its bonus damage to one-handed weapons on the combat tab. It does mention it in the features tab, but that isn't the most helpful. 

**To Reproduce**
1. Create a Fighter character under Class and Level
2. Select Dueling as your Fighting Style at the bottom.
3. Equip a one handed weapon on your sheet.
4. See damage does not increase on any of the combat stats.

**Expected behavior**
The feat is supposed to apply +2 damage to your held weapon if it is one-handed and you do not have a weapon in your offhand.

**Additional context**
It seems this was addressed before, but the person who was fixing it had to move onto other projects.

**Comment by DivertedCircle** [comment] 2020-05-04 23:50
Duplicate of #249.

**Closed as completed by DivertedCircle** 2020-05-04 23:50 UTC
