### ISSUE TITLE
Selection Builder not saving

### ISSUE THREAD

**Issue by Dandaman110** [Orcpub/orcpub#393] opened 2020-05-14 04:23 UTC
This was brought up before, almost exactly a year ago, and I have had this problem a number of times since then so it is clearly not resolved.

**Describe the bug**
Trying to save with any selections actually made results in "You must specify 'Name', 'Option Source Name' " message.

**To Reproduce**
1. Save a selection with no actual selections made
2. Save will be confirmed
3. Make a selection
4. Save will be denied

**Expected behavior**
The selection should be saved.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome

The previous post on this suggested that characters in the name and option source name might be causing it but I am using only letters, so that shouldn't be a problem, and changing the names has not fixed anything.

**Comment by datdamnzotz** [comment] 2020-05-14 14:22
Looks like it is still open
Duplicate of #174 
If you want to make comments, then use the open issue.
Closing

**Closed as completed by datdamnzotz** 2020-05-14 14:22 UTC
Labels: duplicate
