### ISSUE TITLE
Rogue Arcane Trickster spell slots

### ISSUE THREAD

**Issue by CapsReeks** [Orcpub/orcpub#109] opened 2019-03-18 09:48 UTC
> You determine your available spell slots by adding together all your levels in the bard, cleric, druid, sorcerer, and wizard classes, half your levels (rounded down) in the paladin, ranger, and artificer (UA) classes, and a third of your fighter or rogue levels (rounded down) if you have the Eldritch Knight or the Arcane Trickster archetypes. Use this total to determine your spell slots.

 I create a rogue arcane trickster (3) and wizard bladesinger (2) and i can't use slots of 2nd.
I think there is an error in slots. The spellcaster level is 3, but it seems like it is 2.

**Comment by DivertedCircle** [comment] 2019-03-18 13:55
Can you provide a link or screenshots of the character you're having this issue with? I'm unable to replicate it. My attached image shows the proper spell slots.

![image](https://user-images.githubusercontent.com/26470570/54534967-2138e200-4953-11e9-9372-01a7ef06a211.png)

**Comment by CapsReeks** [comment] 2019-03-18 14:33
Hi,
i wrong, i have slots for 2nd level spells



but i can’t choose 2nd level spells



Inviato da Posta per Windows 10

Da: DivertedCircle
Inviato: lunedì 18 marzo 2019 14:55
A: Orcpub/orcpub
Cc: CapsReeks; State change
Oggetto: Re: [Orcpub/orcpub] Rogue Arcane Trickster spell slots (#109)

Can you provide a link or screenshots of the character you're having this issue with? I'm unable to replicate it. My attached image shows the proper spell slots.

**Comment by DivertedCircle** [comment] 2019-03-18 14:43
That would be working as intended then. Spell slots are determined by your combined spellcaster level but individual spells you learn are limited to the spellcasting level of the class you're choosing for. This means that while you have access to second level spell slots you can't yet choose second level spells because neither your arcane trickster or bladesinger class levels are high enough yet. You will need to take arcane trickster to 7th level or bladesinger to 3rd level to unlock second level spells, at which point you would unlock them for that class only. The Player's Handbook spells it out better:

```"You determine what spells you know and can prepare for each class individually, as if you were a single-classed member of that class. If you are a ranger 4/wizard 3, for example, you know three 1st-level ranger spells based on your levels in the ranger class. As 3rd-level wizard, you know three wizard cantrips, and your spellbook contains ten wizard spells, two of which (the two you gained when you reached 3rd level as a wizard) can be 2nd-level spells. If your intelligence is 16, you can prepare six wizard spells from your spellbook.
Each spell you know and prepare is associated with one of your classes, and you use the spellcasting ability of that class when you cast the spell. Similarly, a spellcasting focus, such as a holy symbol, can be used only for the spells from the class associated with that focus.
If a cantrip of yours increases in power at higher levels, the increase is based on your character level, not your level in a particular class." ```

**Comment by datdamnzotz** [comment] 2019-04-07 05:10
Closing.

**Closed as completed by datdamnzotz** 2019-04-07 05:10 UTC
Labels: bug, area/application
