### ISSUE TITLE
skill modifier field too small for double digit values

### ISSUE THREAD

**Issue by Arogen** [Orcpub/orcpub#328] opened 2020-03-09 23:05 UTC
If a skill modifier is +10 or above it doesn't display correctly in the PDF, the field is too small for 3 characters.

To reproduce, create a new character, set the level to 20 and all base stats to 18
check that there are double digit skill bonuses
click on print and generate the PDF
notice the bonus do not appear right for the double digit bonuses

Expected: all three character (the +sign and the two digits) show in the field

Windows 7 / Chrome

A larger field rather than a smaller font would be preferred.

**Comment by datdamnzotz** [comment] 2020-03-29 23:14
@arogen
I'm unable to reproduce the condition, could you provide a screen shot.
This is what I see
![image](https://user-images.githubusercontent.com/3913859/77863596-ccc07780-71e0-11ea-83fc-36ad376a76cd.png)

**Comment by Arogen** [comment] 2020-03-30 01:50
See below (enlarged to 150%)

Deception is +10, slight of hand is +11

If I manually remove the + then they show up fine.  

I have Acrobat Reader DC 2020.006.20042

**Comment by codeGlaze** [comment] 2020-03-30 04:49
Did you email reply or something? Because where the attachment is suppose to be is a garbled mess.

**Comment by Arogen** [comment] 2020-03-30 15:19
I pasted the screen shot into the email body.  I'll try attaching the screen shot (enlarged to 150%) and the pdf instead.

Deception is +10, slight of hand is +11

If I manually remove the + then they show up fine.  

I have Acrobat Reader DC 2020.006.20042

**Comment by datdamnzotz** [comment] 2020-05-07 19:40
Unable to confirm, closing

**Closed as completed by datdamnzotz** 2020-05-07 19:40 UTC
Labels: area/application, area/pdf
