### ISSUE TITLE
[Suggestion] Custom Spells for Homebrew Subclasses

### ISSUE THREAD

**Issue by UltraDaiSenpai** [Orcpub/orcpub#187] opened 2019-06-01 22:27 UTC
Is this an easy implementation? I find, and I'm sure others agree, that when adding homebrew materials to Orcpub/DMV it's simply easier to abandon subclasses that branch into spell casting rather than put them in, simply because of how much of a hassle it is to have a class that naturally doesn't spellcast except for that one subclass that does. Perhaps add the section that asks whether or not the class casts spells to the subclass creator as well?

**Comment by DivertedCircle** [comment] 2019-07-09 21:12
This is a duplicate of #34 .

**Comment by datdamnzotz** [comment] 2019-07-13 17:17
Duplicate #34

**Closed as completed by datdamnzotz** 2019-07-13 17:17 UTC
Labels: duplicate, wontfix
