### ISSUE TITLE
Add Fighting Style builder

### ISSUE THREAD

**Issue by DialDM** [Orcpub/orcpub#448] opened 2020-09-19 03:28 UTC
**Motivation / Use Case**

I do not have the option to add a fighting style, and i know there are many more that the pre determined set. 

**Expected Behavior**

Just button that take you to a fighting style builder page. the page would kind of look like the language builder.

**Comment by datdamnzotz** [comment] 2020-09-30 07:28
Duplicate of #249

**Closed as completed by datdamnzotz** 2020-09-30 07:28 UTC
