### ISSUE TITLE
Cleric Selection Not Working

### ISSUE THREAD

**Issue by ghul13** [Orcpub/orcpub#368] opened 2020-04-29 03:09 UTC
I am experiencing an issue where when I select "cleric" under the Class/Level tab for either a new character or multiclass, the page goes blank and does not reload. When the page is reloaded, it does not register that cleric was selected and reverts to the previous page.

**To Reproduce**
1. Go to the Character Builder page
2. Click on the Class/ Level tab
3. Scroll down to "Cleric"

As mentioned above, the page should go blank and stop loading.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Chrome 81.0.4044.122

**Comment by codeGlaze** [comment] 2020-04-29 14:54
Sounds like you have an error caused by custom content.

Try making a cleric in an incognito window *without* loading any extra content to confirm.

Typically disabling content you've made yourself one "source" at a time will help you find out what's causing the bug.

**Comment by ghul13** [comment] 2020-04-29 15:05
That worked! I'll try to start the process of elimination to find what's causing the problem.

**Comment by ghul13** [comment] 2020-04-29 15:11
Just to help me narrow it down, do you have any idea what sort of extra content might be causing the load failure?

**Comment by codeGlaze** [comment] 2020-04-29 15:15
I would start with anything you made yourself.

I also suggest joining the discord, that'll be faster responses for Homebrew help.

The github is for site bugs, fixes, etc.

**Comment by ghul13** [comment] 2020-04-29 20:41
Ok! I'll join the discord.

**Comment by datdamnzotz** [comment] 2020-05-02 18:06
Orcbrew related.  Closing.

**Closed as completed by datdamnzotz** 2020-05-02 18:06 UTC
Labels: wontfix
