### ISSUE TITLE
Issues with Character Sharing

### ISSUE THREAD

**Issue by leastinformednerd** [Orcpub/orcpub#302] opened 2020-01-27 03:51 UTC
If you open another person's character in through the link it will log you out every few minutes. This also occurs on the party screen and combat tracker. I had all the relevant orcbrew files.

**Comment by datdamnzotz** [comment] 2020-03-20 07:18
Duplicate of #338, 338 has more info, closing.

**Closed as completed by datdamnzotz** 2020-03-20 07:18 UTC
Labels: bug, area/application
