### ISSUE TITLE
Eldritch Invocation Prerequisites

### ISSUE THREAD

**Issue by MutantYoshi** [Orcpub/orcpub#397] opened 2020-05-31 01:41 UTC
One feature I would like is for custom Eldritch Invocations to have prerequisite options such as being a certain level, picking a certain Pact Boon, or knowing a certain spell.  There are those already built in that have those prerequisites, but we can't do that ourselves.

**Comment by DivertedCircle** [comment] 2020-05-31 19:26
Duplicate of #57. Closing.

**Closed as completed by DivertedCircle** 2020-05-31 19:26 UTC
