### ISSUE TITLE
Constitution score uses Caduceus instead of Rod of Asclepius for imagery

### ISSUE THREAD

**Issue by TechyShishy** [Orcpub/orcpub#602] opened 2024-02-18 15:25 UTC
**Describe the bug**
The little icon above Constitution scores uses a symbol known as a [Caduceus](https://en.wikipedia.org/wiki/Caduceus), rather than the medically relevant [Rod of Asclepius](https://en.wikipedia.org/wiki/Rod_of_Asclepius).  This is a common misconception (see: https://en.wikipedia.org/wiki/Caduceus_as_a_symbol_of_medicine), but Orcpub would benefit from using the correct symbol

**Screenshots**

![Screenshot from 2024-02-18 07-18-23](https://github.com/Orcpub/orcpub/assets/848519/b9a3472f-f375-4ce3-ba04-546ff85d2256)

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser: Chrome
 - Version: 121.0.6167.184

**Comment by codeGlaze** [comment] 2024-03-09 22:11
lol this might just be a limit to the icon library we use.
I'll take a look ;)

**Comment by codeGlaze** [comment] 2024-03-11 17:35
Ha, apparently a duplicate of #573 too

**Closed as completed** 2024-03-28 16:21 UTC
